baseURL = 'https://www.plbear.com/'
languageCode = 'zh-cn'
title = 'Plbear | Cuz Penguin QQ'
defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true
theme = 'PaperMod'
enableRobotsTXT = true
enableEmoji = true
[pagination]
  pagerSize = 10
summaryLength = 50

[params]
  description = 'Food And Freedom. Make my own world a better place.'
  author = 'IYABAO'
  keywords = ['技术博客', '生活随笔', 'Plbear']
  env = 'production'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = true
  tocopen = false

[params.homeInfoParams]
  Title = "Plbear | Cuz Penguin QQ"
  Content = "Food And Freedom. Make my own world a better place."

[params.assets]
  disableHLJS = true

[[params.socialIcons]]
  name = 'github'
  url = 'https://github.com/IYABAO'
[[params.socialIcons]]
  name = 'rss'
  url = '/index.xml'

[params.search]
  enable = true

[menu]
  [[menu.main]]
    name = '首页'
    url = '/'
    weight = 1
  [[menu.main]]
    name = '归档'
    url = '/archives/'
    weight = 2
  [[menu.main]]
    name = '标签'
    url = '/tags/'
    weight = 3
  [[menu.main]]
    name = '分类'
    url = '/categories/'
    weight = 4
  [[menu.main]]
    name = '关于'
    url = '/about/'
    weight = 5

[markup]
  [markup.highlight]
    style = 'github'
    lineNos = true
    codeFences = true
    guessSyntax = true
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4

[outputs]
  home = ['HTML', 'RSS', 'JSON']
  section = ['HTML', 'RSS']

[taxonomies]
  tag = 'tags'
  category = 'categories'
